-- MySQL Script generated by MySQL Workbench
-- Fri Jan 18 14:26:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema manhistdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manhistdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manhistdb` DEFAULT CHARACTER SET latin1 ;
USE `manhistdb` ;

-- -----------------------------------------------------
-- Table `manhistdb`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manhistdb`.`portfolio` (
  `image_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(65) CHARACTER SET 'utf8' NOT NULL,
  `cat` VARCHAR(65) CHARACTER SET 'utf8' NOT NULL,
  `img` VARCHAR(65) CHARACTER SET 'utf8' NOT NULL,
  `shared` DATETIME NOT NULL,
  PRIMARY KEY (`image_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manhistdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manhistdb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` ENUM('Author', 'Admin') NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manhistdb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manhistdb`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `views` INT(11) NOT NULL DEFAULT '0',
  `image` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `published` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `manhistdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manhistdb`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manhistdb`.`topics` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf32' COLLATE 'utf32_unicode_ci' NULL DEFAULT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manhistdb`.`post_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manhistdb`.`post_topic` (
  `id` INT(11) NOT NULL,
  `post_id` INT(11) NULL DEFAULT NULL,
  `topic_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `post_id` (`post_id` ASC) VISIBLE,
  INDEX `topic_id` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `post_topic_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `manhistdb`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_topic_ibfk_2`
    FOREIGN KEY (`topic_id`)
    REFERENCES `manhistdb`.`topics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
